spring.application.name=Machine

spring.datasource.url=jdbc:postgresql://ep-still-mountain-aqibxu8j-pooler.c-8.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_JikrdS34HRve

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true

server.port=1608

jwt.secretKey=Rx4PmASMnloHRJT7C0cwpfXVHsv+isxqF84/GygMMxg=
server.forward-headers-strategy=framework