spring.application.name=Machine
spring.datasource.url=jdbc:postgresql://localhost:5432/V3
spring.datasource.username=postgres
spring.datasource.password=sql
management.endpoints.web.exposure.include=metrics,prometheus
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
server.port=1608
